### ISSUE TITLE
no BF1BotModInjector.exe under the bin

### ISSUE THREAD

**Issue by arkilis** [cookgreen/BF1BotMod#1]

**Comment by arkilis** [comment]
**update:** after compile a exe. With the BF1 running, and run the `BF1BotModInjector.exe`, nothing happened.

**Comment by ttt104524** [comment]
I can't find the exe file, it seems like it hasn't been uploaded

**Comment by cookgreen** [comment]
ok, I will fix that

**Comment by cookgreen** [comment]
@arkilis Fixed

**Comment by gftrg345335** [comment]
BF1BotModInjector.exe все ещё нету в bin

**Comment by cookgreen** [comment]
> BF1BotModInjector.exe все ещё нету в bin

Вам нужно скомпилировать весь проект

**Comment by fredsmil111** [comment]
The main file cant be compile becouse of error

**Comment by fredsmil111** [comment]
![image](https://github.com/user-attachments/assets/30811a6e-a8be-4988-9b19-46e402db735f)

**Comment by cookgreen** [comment]
> ![image](https://private-user-images.githubusercontent.com/176918430/353070549-30811a6e-a8be-4988-9b19-46e402db735f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjEzMjksIm5iZiI6MTcyMjI2MTAyOSwicGF0aCI6Ii8xNzY5MTg0MzAvMzUzMDcwNTQ5LTMwODExYTZlLWE4YmUtNDk4OC05YjE5LTQ2ZTQwMmRiNzM1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMzUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTNiYzVmZTg4NWE1YzIwMTVhOTgwOTM5ODgyOTZkY2RlMWNjMTVhMTc0N2M2NjIzZDc2OWE5NTNjMjI4YWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b9fd2sJQAvQalYYadP-b7LwA0RT_iPOZbLbL8BovRz0)

Well, you need to install the Windows SDK

**Comment by fredsmil111** [comment]
> > ![image](https://private-user-images.githubusercontent.com/176918430/353070549-30811a6e-a8be-4988-9b19-46e402db735f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjEzMjksIm5iZiI6MTcyMjI2MTAyOSwicGF0aCI6Ii8xNzY5MTg0MzAvMzUzMDcwNTQ5LTMwODExYTZlLWE4YmUtNDk4OC05YjE5LTQ2ZTQwMmRiNzM1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMzUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTNiYzVmZTg4NWE1YzIwMTVhOTgwOTM5ODgyOTZkY2RlMWNjMTVhMTc0N2M2NjIzZDc2OWE5NTNjMjI4YWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b9fd2sJQAvQalYYadP-b7LwA0RT_iPOZbLbL8BovRz0)
> 
> Well, you need to install the Windows SDK

already but problem dosent gone

**Comment by fredsmil111** [comment]
So how I can fix my problem? I download the Windows SDK but the problem dosent gone

**Comment by EdiVisuals** [comment]
Hi,

I'm really interested in using the BF1BotMod, but I don't have much programming knowledge. I've been trying to compile the project myself, but I keep running into errors—especially the one where it says it cannot find minhook.lib.

I downloaded MinHook and tried to compile it, then added the generated .lib file to my project, but I'm still not able to make it work. I'm not sure if I'm placing the file correctly or missing something in the configuration.

My question is:
Is there a precompiled version of the mod (DLL or EXE) that I can just download and use without having to build the project myself? Or is it necessary to compile everything from source in order to get it running?

Thank you for any help you can provide!
